### ISSUE TITLE
__eq__ and __ne__ methods for Edge class?

### ISSUE THREAD

**Issue by nickm1990** [pranavtotla/polygonlite#1]
**Is your feature request related to a problem? Please describe.**
It would be great if I have a method to check if two edges are same.

**Describe the solution you'd like**
__ eq __ and __ ne __ methods for Edge class.

**Describe alternatives you've considered**
Individually checking the points of the edge, but when I'm talking about thousands of edges, it would be simpler to have a direct method.

**Comment by pranavtotla** [comment]
Okay, sounds reasonable. I'll do that and release another version!
